apiVersion: v1
kind: Service
metadata:
  name: cl-config-service
spec:
  
  selector:
    app: configserver
    department: sabb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888