apiVersion: v1
kind: Service
metadata:
  name: np-config-service
spec:
  type: NodePort
  selector:
    app: configserver
    department: sabb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888