apiVersion: v1
kind: Service
metadata:
  name: cl-config-service
spec:
  
  selector:
    app: cfgserver
    department: sabbv2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080